apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: domino
spec:
  terminationGracePeriodSeconds: 0
  restartPolicy: Always
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh","-c","trap 'exit 0' TERM INT; while :; do sleep 3600; done"]
    imagePullPolicy: Always

