apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-with-disk
  namespace: domino
spec:
  terminationGracePeriodSeconds: 0
  restartPolicy: Always
  containers:
  - name: ubuntu
    image: ubuntu 
    imagePullPolicy: Always 
    command: ["/bin/sh","-c"]
    args:
      - sleep infinity
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: ubuntu-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pvc
  namespace: domino
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

